### Import packages

In [103]:
import pandas as pd
import numpy as np

### Import database

In [104]:
df = pd.read_csv('titanic.csv', sep=',')
df.head()

,PassengerId,Survived,Pclass,Lname,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund,Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen,Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen,Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S

### Visualize the database

In [105]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Lname        156 non-null    object
 4   Name         156 non-null    object
 5   Sex          156 non-null    object
 6   Age          126 non-null    float64
 7   SibSp        156 non-null    int64
 8   Parch        156 non-null    int64
 9   Ticket       156 non-null    object
 10  Fare         156 non-null    float64
 11  Cabin        31 non-null     object
 12  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 16.0+ KB

In [107]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Lname', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Searching in the database

In [119]:
df['Travelalone'] = np.where( ( df['SibSp'] + df['Parch'] ) > 0, 0, 1 ).astype('uint8')

print(df['Travelalone'])

0      0
1      0
2      1
3      0
4      1
      ..
151    0
152    1
153    0
154    1
155    0
Name: Travelalone, Length: 156, dtype: uint8

In [120]:
df1 = df.drop( ['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'], axis=1 )

In [121]:
df1.isna().sum()

Survived       0
Pclass         0
Lname          0
Sex            0
Age            0
Fare           0
Embarked       1
Travelalone    0
dtype: int64

In [122]:
df['Age'].fillna( df1['Age'].median( skipna=True ), inplace=True )

In [112]:
df1.head()

   Survived  Pclass      Lname     Sex   Age     Fare Embarked  Travelalone
0         0       3     Braund    male  22.0   7.2500        S            0
1         1       1    Cumings  female  38.0  71.2833        C            0
2         1       3  Heikkinen  female  26.0   7.9250        S            1
3         1       1   Futrelle  female  35.0  53.1000        S            0
4         0       3      Allen    male  35.0   8.0500        S            1

### First analysis

In [113]:
df_titanic = pd.get_dummies(df1, columns=['Pclass', 'Embarked', 'Sex'], drop_first=True )
df_titanic.head()

,Survived,Lname,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,Braund,22.0,7.2500,0,False,True,False,True,True
1,1,Cumings,38.0,71.2833,0,False,False,False,False,False
2,1,Heikkinen,26.0,7.9250,1,False,True,False,True,False
3,1,Futrelle,35.0,53.1000,0,False,False,False,True,False
4,0,Allen,35.0,8.0500,1,False,True,False,True,True

In [114]:
X = df_titanic.drop( ['Survived'], axis=1 )
y = df_titanic['Survived']

### Applying preprocessing

In [124]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [125]:
trans_MM = MinMaxScaler()
trans_SS = StandardScaler()

In [126]:
X.dtypes

Lname           object
Age            float64
Fare           float64
Travelalone      uint8
Pclass_2          bool
Pclass_3          bool
Embarked_Q        bool
Embarked_S        bool
Sex_male          bool
dtype: object

In [127]:
## transform the data
df_MM = trans_MM.fit_transform(X)
pd.DataFrame(df_MM)

ValueError: could not convert string to float: 'Braund'

In [123]:
df_SS = trans_SS.fit_transform(X)
pd.DataFrame(df_SS)

ValueError: could not convert string to float: 'Braund'